### PR TITLE
Add support for ED25519 scalar multiplication

### PR DESCRIPTION
**Pull request by razvand**
Add libsodium reference implementation in `scalarmult_ed25519_ref10.c`.

### CODE REVIEW

**Review by flpostolache — COMMENTED** [review]
Looks good!

Reviewed-by: Florin Postolache florin.postolache80@gmail.com

**Comment by razvand** [comment]
@maniatro111 , please also approve this by going to `Files changed` -> `Review changes`. Add the reviewed by message there.

**Comment by razvand** [comment]
@michpappas , please approve this if it's OK with you.

**Review by flpostolache — APPROVED** [review]
Looks good!

Reviewed-by: Florin Postolache florin.postolache80@gmail.com

**Comment by michpappas** [comment]
Hi @razvand, thanks for that. Two things:
1. I think any components enabled must come with the relevant tests. `scalarmult_ed25519_ref10.c` is covered by `tests/default/scalarmult_ed25519.c`. Please have a look at `lib-libsodium/patches/` and `lib-libsodium/src/uk_sodium_test.c` to see how we deploy tests.
2. Currently we build the components that would be available if someone configured libsodium with `--enable=minimal` (see [README.md](https://github.com/unikraft/lib-libsodium/blob/staging/README.md)). There are two ways forward here: Either enable all components, or start off with minimal and enable additional components on a per-need basis. I don't have a strong opinion, but either way README.md must be clear of what the user gets.

**Comment by razvand** [comment]
I will close this. If additional features are required, we will create a larger PR.

**Pull request closed without merging**
