### PR TITLE
Add the internal 'posix-event' library as a dependency

### LINKED ISSUE #5: Possible missing internal dependency
As part of working on [lib-mimalloc#2](https://github.com/unikraft/lib-mimalloc/issues/2), trying to run the [app-helloworld](https://github.com/unikraft/app-helloworld) app with this change to the Makefile

```diff
diff --git a/Makefile b/Makefile
index 5426bae..3e13e23 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 UK_ROOT ?= $(PWD)/../../unikraft
 UK_LIBS ?= $(PWD)/../../libs
-LIBS :=
+LIBS := $(UK_LIBS)/lib-newlib:$(UK_LIBS)/lib-libsodium

 all:
        @$(MAKE) -C $(UK_ROOT) A=$(PWD) L=$(LIBS)
```

Fails to link with the following error `undefined reference to 'poll'`
```
  LD      app-helloworld-libsodium_kvm-x86_64.dbg
/usr/bin/ld: /home/ubuntu/usoc22/apps/app-helloworld-libsodium/build/app-helloworld-libsodium_kvm-x86_64.o: in function `randombytes_block_on_dev_random':
/home/ubuntu/usoc22/apps/app-helloworld-libsodium/build/libsodium/origin/libsodium-1.0.18/src/libsodium/randombytes/internal/randombytes_internal_random.c:265: undefined reference to `poll'
/usr/bin/ld: /home/ubuntu/usoc22/apps/app-helloworld-libsodium/build/app-helloworld-libsodium_kvm-x86_64.o: in function `randombytes_block_on_dev_random':
/home/ubuntu/usoc22/apps/app-helloworld-libsodium/build/libsodium/origin/libsodium-1.0.18/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c:166: undefined reference to `poll'
collect2: error: ld returned 1 exit status
make[3]: *** [/home/ubuntu/usoc22/unikraft/plat/kvm/Linker.uk:24: /home/ubuntu/usoc22/apps/app-helloworld-libsodium/build/app-helloworld-libsodium_kvm-x86_64.dbg] Error 1
make[2]: *** [Makefile:1016: sub-make] Error 2
make[1]: *** [Makefile:32: _all] Error 2
make[1]: Leaving directory '/home/ubuntu/usoc22/unikraft'
make: *** [Makefile:6: all] Error 2
```

If this is reproducible, i have included a patch for updating the dependencies list

```diff
diff --git a/Config.uk b/Config.uk
index be95b8a..27af070 100644
--- a/Config.uk
+++ b/Config.uk
@@ -3,6 +3,7 @@ menuconfig LIBSODIUM
 	default n
 	select LIBNEWLIBC
 	select LIBUKSWRAND
+	select LIBPOSIX_EVENT
 
 if LIBSODIUM
 	config LIBSODIUM_TEST
diff --git a/README.md b/README.md
index e362218..3246fe1 100644
--- a/README.md
+++ b/README.md
@@ -12,6 +12,7 @@ equivalent state of configuring libsodium using `configure --enable-minimal`.
 libsodium on Unikraft depends on the following Unikraft libraries:
 * lib-newlib (external)
 * ukswrand (internal)
+* posix-event (internal)
 
 Both dependencies are automatically enabled via KConfig.
  
```

### PR DESCRIPTION
**Pull request by hchandad**
Related Issue: #5 

Selects 'posix-event' in Config.uk and updates README.md accordingly

*Signed-off-by: Hamza Chandad <hchandad@proton.me>*

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
Looks good, thank you.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — CHANGES_REQUESTED** [review]
Thanks for this, @hchandad . Please add a description line to the commit message that explains the need for the `posix-event` library dependency. You can follow the description in [the equivalent commit for `lib-redis`](https://github.com/unikraft/lib-redis/pull/6/commits/e4e2eafe526f7cb82b697af71cb015e600679012).

**Comment by hchandad** [comment]
@razvand i updated the commit message.

**Review by razvand — APPROVED** [review]
Thanks, @hchandad . This works.

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Pull request closed without merging**
